/**
 * Marker of what produced an entity. Written by the backend into the custom fields of the business object,
 * see `step.core.entities.EntityOrigin`.
 */
export const ENTITY_ORIGIN_CUSTOM_FIELD = 'origin';

/** Value of the origin marker for entities generated by the AI agent. */
export const ENTITY_ORIGIN_AI = 'ai';

export const isAiGeneratedEntity = (entity?: { customFields?: Record<string, any> }): boolean =>
  entity?.customFields?.[ENTITY_ORIGIN_CUSTOM_FIELD] === ENTITY_ORIGIN_AI;
