/**
 * Key of the marker telling what produced an entity, read from its `metadata`
 * (see `step.core.accessors.AbstractIdentifiableObject`).
 */
export const ENTITY_ORIGIN_KEY = 'origin';

/** Value of the origin marker for entities generated by the AI agent. */
export const ENTITY_ORIGIN_AI = 'ai';

/**
 * The value is compared case-insensitively, because the metadata of an entity coming from an automation package is
 * written by hand as well as by the agent.
 */
export const isAiGeneratedEntity = (entity?: { metadata?: Record<string, any> }): boolean => {
  const origin = entity?.metadata?.[ENTITY_ORIGIN_KEY];
  return typeof origin === 'string' && origin.toLowerCase() === ENTITY_ORIGIN_AI;
};
