#!/bin/bash

## add timestamp to scripts.sh in order to prevent caching of legacy code
SCRIPTSJS_FILENAME_BEFORE=scripts.js
SCRIPTSJS_FILE_FOLDER_OS=dist/step-app/app
SCRIPTSJS_FILE_FOLDER_EE=dist/step-frontend/src/lib/angularjs/app

SCRIPTSJS_HASH=$(sha1sum $SCRIPTSJS_FILE_FOLDER_OS/$SCRIPTSJS_FILENAME_BEFORE | awk '{ print $1 }')
SCRIPTSJS_FILENAME_AFTER=scripts-$SCRIPTSJS_HASH.js

LEGACY_JS_LOADER_FILE_NAME=postbuild-load-legacy.js

mv $SCRIPTSJS_FILE_FOLDER_OS/$SCRIPTSJS_FILENAME_BEFORE $SCRIPTSJS_FILE_FOLDER_OS/$SCRIPTSJS_FILENAME_AFTER
mv $SCRIPTSJS_FILE_FOLDER_EE/$SCRIPTSJS_FILENAME_BEFORE $SCRIPTSJS_FILE_FOLDER_EE/$SCRIPTSJS_FILENAME_AFTER
cp $LEGACY_JS_LOADER_FILE_NAME $SCRIPTSJS_FILE_FOLDER_OS
cp $LEGACY_JS_LOADER_FILE_NAME $SCRIPTSJS_FILE_FOLDER_EE
sed -i "s/_HASHED_LEGACY_SCRIPTS_JS_/$SCRIPTSJS_FILENAME_AFTER/g" $SCRIPTSJS_FILE_FOLDER_OS/$LEGACY_JS_LOADER_FILE_NAME
sed -i "s/_HASHED_LEGACY_SCRIPTS_JS_/$SCRIPTSJS_FILENAME_AFTER/g" $SCRIPTSJS_FILE_FOLDER_EE/$LEGACY_JS_LOADER_FILE_NAME
