#!/bin/bash

## add timestamp to scripts.sh in order to prevent caching of legacy code
SCRIPTSJS_FILENAME_BEFORE=scripts.js
SCRIPTSJS_FILE_FOLDER=dist/step-app/app

SCRIPTSJS_HASH=$(sha1sum $SCRIPTSJS_FILE_FOLDER/$SCRIPTSJS_FILENAME_BEFORE | awk '{ print $1 }')
SCRIPTSJS_FILENAME_AFTER=scripts-$SCRIPTSJS_HASH.js

LEGACY_JS_LOADER_FILE_NAME=postbuild-load-legacy.js
INDEX_FILE_DIR=dist/step-app

mv $SCRIPTSJS_FILE_FOLDER/$SCRIPTSJS_FILENAME_BEFORE $SCRIPTSJS_FILE_FOLDER/$SCRIPTSJS_FILENAME_AFTER
cp $LEGACY_JS_LOADER_FILE_NAME $INDEX_FILE_DIR
sed -i "s/_HASHED_LEGACY_SCRIPTS_JS_/$SCRIPTSJS_FILENAME_AFTER/g" $INDEX_FILE_DIR/$LEGACY_JS_LOADER_FILE_NAME
