export enum CompareCondition {
  GREATER_THAN = 'Gt',
  GREATER_THAN_OR_EQUAL = 'Gte',
  LOWER_THAN = 'Lt',
  LOWER_THAN_OR_EQUAL = 'Lte',
  EQUALS = 'Equals',
  AND = 'And',
  FALSE = 'False',
  FULL_TEXT = 'FullText',
  IN = 'In',
  NOT = 'Not',
  OR = 'Or',
  REGEX = 'Regex',
  TRUE = 'True',
}
