export enum ArtefactClass {
  KEYWORD = 'CallKeyword',
  TEST_CASE = 'TestCase',
  SLEEP = 'Sleep',
  ECHO = 'Echo',
  WAIT_FOR_EVENT = 'WaitForEvent',
  THREAD_GROUP = 'ThreadGroup',
  FOR = 'For',
  FOR_EACH = 'ForEach',
  SEQUENCE = 'Sequence',
  TEST_SCENARIO = 'TestScenario',
  TEST_SET = 'TestSet',
  CHECK = 'Check',
  ASSERT = 'Assert',
  PERFORMANCE_ASSERT = 'PerformanceAssert',
}
